# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gamers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(choices=[('WINDOWS', 'Windows'), ('MAC', 'Mac'), ('LINUX', 'LINUX'), ('PS4', 'PLAYSTATION 4'), ('XBOX ONE', 'XBOX ONE'), ('PS3', 'PLAYSTATION 3'), ('XBOX 360', 'XBOX 360')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='game',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='game',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='game',
            name='publisher',
        ),
        migrations.AlterField(
            model_name='game',
            name='homepage',
            field=models.URLField(),
        ),
        migrations.AddField(
            model_name='publisher',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gamers.Game'),
        ),
        migrations.AddField(
            model_name='platform',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gamers.Game'),
        ),
        migrations.AddField(
            model_name='pictures',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gamers.Game'),
        ),
        migrations.AddField(
            model_name='genre',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gamers.Game'),
        ),
        migrations.AddField(
            model_name='developer',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gamers.Game'),
        ),
    ]
