# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamers', '0002_auto_20170223_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='steam_id',
            field=models.IntegerField(null=True),
        ),
    ]
