# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamers', '0003_auto_20170502_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Game',
            new_name='game',
        ),
        migrations.AlterField(
            model_name='review',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='write_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
