# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gamers', '0003_game_steam_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='title',
        ),
    ]
