# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 10:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_django', '0006_partial'),
        ('Gamers', '0004_auto_20170308_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('content', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('Game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gamers.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Pictures',
            new_name='Picture',
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Gamer',
        ),
    ]
