# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 08:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gamers', '0004_auto_20170519_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([('user', 'game')]),
        ),
    ]
