# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamers', '0005_auto_20170525_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
