# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gamers', '0006_auto_20170525_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Screenshot_url', models.URLField()),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gamers.Game')),
            ],
        ),
        migrations.RemoveField(
            model_name='picture',
            name='game',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
