# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gamers', '0007_auto_20170527_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screenshot',
            old_name='Screenshot_url',
            new_name='screenshot_url',
        ),
    ]
