# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamers', '0010_auto_20170607_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='screenshot_url',
            field=models.URLField(default='http://www.visitcrickhowell.co.uk/wp-content/themes/cricwip/images/noimage_595.png'),
        ),
        migrations.AddField(
            model_name='game',
            name='Tags',
            field=models.ManyToManyField(to='Gamers.Tag'),
        ),
    ]
