# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 06:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gamers', '0013_auto_20170627_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThumbUpDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb_up_down', models.IntegerField(choices=[(1, 'Thumb Up'), (0, 'Nothing'), (-1, 'Thumb Down')])),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='review',
            name='like',
        ),
        migrations.AddField(
            model_name='thumbupdown',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gamers.Review'),
        ),
        migrations.AddField(
            model_name='thumbupdown',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
